# Generated by Django 6.0.7 on 2026-08-01 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_thirdcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('p_detail', models.TextField()),
                ('p_image', models.ImageField(upload_to='images')),
                ('p_rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('status', models.BooleanField(default=True)),
                ('stock', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.category')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.subcategory')),
                ('thirdcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.thirdcategory')),
            ],
        ),
    ]
