# Generated by Django 6.1 on 2026-08-09 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_order_payment_method_order_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='subcategory_image',
            field=models.ImageField(blank=True, null=True, upload_to='subcategory/'),
        ),
        migrations.AddField(
            model_name='thirdcategory',
            name='thirdcategory_image',
            field=models.ImageField(blank=True, null=True, upload_to='thirdcategory/'),
        ),
    ]
